- name: skill
  color: '0e8a16'
- name: project
  color: '1d76db'
- name: resource
  color: '5319e7'
- name: priority:high
  color: 'b60205'
- name: priority:medium
  color: 'd4c5f9'
- name: priority:low
  color: 'fef2c0'
- name: in-progress
  color: '0e8a16'
- name: blocked
  color: 'ffd33d'
- name: done
  color: '6f42c1'
- name: difficulty:easy
  color: 'a2eeef'
- name: difficulty:medium
  color: 'fbca04'
- name: difficulty:hard
  color: 'b60205'
- name: needs-review
  color: 'c2e0ff'
